### PR TITLE
chore: add an npm script for tns preview

### PR DESCRIPTION
**Pull request by sebawita**
The new npm script will allow devs to call `npm run preview`, which will execute `tns preview --bundle`

### CODE REVIEW

**Comment by sis0k0** [comment]
That's a great idea! Preview is quite powerful when converting web projects. I would even go as far as naming the script `npm run mobile`. What do you think?

**Comment by sebawita** [comment]
I like the idea of `npm run mobile`. But I am not sure if that wouldn't be too confusing vs `npm run android`, as the behaviour is different. While with **preview** that could be Googled on 🤔

**Comment by sebawita** [comment]
Yeah I like that. Let me update the PR quickly

**Comment by sebawita** [comment]
I've also added it to the `ng new --shared` schematic

**Pull request merged**
