### PR TITLE
feat: basic update for @nativescript/angular@9.0.0

### LINKED ISSUE #275: Update to Angular 9
Will you guys release an update of this to angular 9?

### PR DESCRIPTION
**Pull request by d-koppenhagen**
## PR Checklist

- [ ] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA].
- [ ] All existing tests are passing: https://github.com/NativeScript/nativescript-schematics/blob/master/CONTRIBUTING.md#running-tests.
- [x] Tests for the changes are included.

## What is the current behavior?

Running the current schematics with an Angular 9 project needs some manual changes after it:
https://github.com/NativeScript/nativescript-angular/wiki/Updating-and-developing-for-@nativescript-angular-v9-with-Ivy-or-without

## What is the new behavior?

The changes will add the manual steps to the schematics so that they will work immediately with angular9.

Fixes/Implements/Closes #275.

BREAKING CHANGES:

Angular 9 is required.

[CLA]: http://www.nativescript.org/cla

### CODE REVIEW

**Comment by d-koppenhagen** [comment]
@NathanWalker let's start supporting Angular 9. Would be great to check my changes in detail.

**Comment by NathanWalker** [comment]
@d-koppenhagen excellent start here! Thank you - we'll collaborate here 👍

**Comment by d-koppenhagen** [comment]
@NathanWalker there are still two tests failing:

It seems that there is some logic removing one Module in case the other is used.
In the old version the imports came from separate modules but now they are all from `@nativescript/angular`.

```text
**************************************************
*                    Failures                    *
**************************************************

1) Refactor NsNg Modules Schematic when a feature module has both NativeScriptModule and NativeScriptAnimationsModule imported should remove the NativeScriptAnimationsModule import
  - Expected '
          import { , NativeScriptCommonModuleNativeScriptAnimationsModule } from "@nativescript/angular";
          import { NgModule, NO_ERRORS_SCHEMA } from "@angular/core";

          @NgModule({
            imports: [
              NativeScriptCommonModule,,
            ],
            schemas: [NO_ERRORS_SCHEMA]
          })
          export class FeatureModule { }
        ' not to match 'NativeScriptAnimationsModule'.

2) Refactor NsNg Modules Schematic when a feature module has both NativeScriptModule and NativeScriptAnimationsModule imported should import the NativeScriptCommonModule to the feature module
  - Expected '
          import { , NativeScriptCommonModuleNativeScriptAnimationsModule } from "@nativescript/angular";
          import { NgModule, NO_ERRORS_SCHEMA } from "@angular/core";

          @NgModule({
            imports: [
              NativeScriptCommonModule,,
            ],
            schemas: [NO_ERRORS_SCHEMA]
          })
          export class FeatureModule { }
        ' to match 'import { NativeScriptCommonModule } from "@nativescript/angular"'.

Executed 151 of 151 specs (2 FAILED) in 11 secs.
```

I couldn't dig deeper into it until now.

**Comment by d-koppenhagen** [comment]
Oh and will `nativescript-dev-webpack` find also a new place in the `@nativescript` scope?
So probably: `@nativescript/dev-webpack` in the near future?

**Comment by NathanWalker** [comment]
@d-koppenhagen Yes on webpack. That will become `@nativescript/webpack` this summer.

**Comment by d-koppenhagen** [comment]
@NathanWalker okay, the breaking stuff was my faulf: I also adjusted the Angular CLI migartion script from previous version which should stay the same as before as they will be applied step by step. Still open: Migration script from current version to new version

**Pull request merged**
